/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {colors: {
        "surface-container-highest": "#e5e2d9",
        "surface-variant": "#e5e2d9",
        "primary": "#37563b",
        "on-tertiary-fixed": "#32101b",
        "on-error": "#ffffff",
        "on-surface": "#1c1c16",
        "tertiary": "#6e434e",
        "on-secondary-container": "#6e5f5f",
        "secondary-container": "#efdbdb",
        "on-tertiary-container": "#ffdfe5",
        "inverse-surface": "#31312a",
        "primary-fixed-dim": "#acd0ad",
        "on-secondary-fixed": "#231919",
        "on-primary": "#ffffff",
        "surface-tint": "#466649",
        "tertiary-container": "#895a66",
        "primary-container": "#4f6f52",
        "tertiary-fixed": "#ffd9e1",
        "error": "#ba1a1a",
        "secondary": "#695b5b",
        "background": "#fcf9ef",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f4ea",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f4f1e7",
        "secondary-fixed-dim": "#d5c2c2",
        "surface-bright": "#fcf9ef",
        "on-tertiary-fixed-variant": "#643a46",
        "tertiary-fixed-dim": "#f1b7c5",
        "on-primary-fixed": "#03210b",
        "outline-variant": "#c2c8bf",
        "error-container": "#ffdad6",
        "surface": "#fcf9ef",
        "on-background": "#1c1c16",
        "surface-container": "#f1eee4",
        "outline": "#737971",
        "on-primary-container": "#ccf0cc",
        "surface-container-high": "#ebe8de",
        "on-primary-fixed-variant": "#2f4e33",
        "primary-fixed": "#c8ecc8",
        "on-error-container": "#93000a",
        "on-surface-variant": "#424841",
        "surface-dim": "#dddad0",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#f2dedd",
        "on-secondary-fixed-variant": "#514444",
        "inverse-primary": "#acd0ad"
      },
    fontFamily: {
        inter: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
